[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"
  # Garantir que o node não engasga em grandes operações PDF
  NODE_OPTIONS = "--max-old-space-size=4096"

# Configuração para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para otimizar CDN e caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Permitir CORS para os workers do PDF.js
[[headers]]
  for = "/*.worker.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"
